packages:
  - apps/*
  - packages/*
  - tools/*
publicHoistPattern:
  - "*prettier*"
catalog:
  "@changesets/cli": ^2.29.4
  "@eslint/js": ^9.25.0
  "@hookform/resolvers": ^5.0.1
  "@nestjs/cli": ^11.0.0
  "@nestjs/common": ^11.0.1
  "@nestjs/core": ^11.0.1
  "@nestjs/platform-express": ^11.0.1
  "@nestjs/schematics": ^11.0.0
  "@nestjs/testing": ^11.0.1
  "@next/eslint-plugin-next": ^15.3.2
  "@radix-ui/react-accordion": ^1.2.10
  "@radix-ui/react-avatar": ^1.1.9
  "@radix-ui/react-checkbox": ^1.3.1
  "@radix-ui/react-collapsible": ^1.1.10
  "@radix-ui/react-dropdown-menu": ^2.1.14
  "@radix-ui/react-label": ^2.1.6
  "@radix-ui/react-scroll-area": ^1.2.8
  "@radix-ui/react-select": ^2.2.4
  "@radix-ui/react-separator": ^1.1.6
  "@radix-ui/react-slot": ^1.2.2
  "@radix-ui/react-tabs": ^1.1.11
  "@radix-ui/react-toggle": ^1.1.8
  "@radix-ui/react-toggle-group": ^1.1.9
  "@svgr/webpack": ^8.1.0
  "@swc/cli": ^0.6.0
  "@swc/core": ^1.10.7
  "@tailwindcss/postcss": ^4.1.6
  "@types/express": ^5.0.0
  "@types/jest": ^29.5.14
  "@types/node": ^22.10.7
  "@types/react": 19.1.4
  "@types/react-dom": 19.1.5
  "@types/supertest": ^6.0.2
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  eslint: ^9.26.0
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.5.3
  globals: ^16.1.0
  husky: ^9.1.7
  jest: ^29.7.0
  lint-staged: ^16.0.0
  lucide-react: ^0.510.0
  next: ^15.3.2
  next-themes: ^0.4.6
  postcss: ^8.5.3
  prettier: ^3.5.3
  prettier-plugin-organize-imports: ^4.1.0
  prettier-plugin-tailwindcss: ^0.6.11
  react: ^19.1.0
  react-dom: ^19.1.0
  react-hook-form: ^7.56.3
  reflect-metadata: ^0.2.2
  rxjs: ^7.8.1
  shiki: ^3.4.1
  source-map-support: ^0.5.21
  supertest: ^7.0.0
  syncpack: ^13.0.4
  tailwind-merge: ^3.3.0
  tailwindcss: ^4.1.6
  ts-jest: ^29.2.5
  ts-loader: ^9.5.2
  ts-node: ^10.9.2
  tsconfig-paths: ^4.2.0
  tsup: ^8.4.0
  turbo: ^2.5.3
  tw-animate-css: ^1.2.9
  typescript: ^5.7.3
  typescript-eslint: ^8.32.1
  use-debounce: ^10.0.4
  zod: ^3.24.4
