export { default as CTASection } from './CTASection'
export { default as FAQSection } from './FAQSection'
export { default as HeroSection } from './HeroSection'
export { default as HowItWorksSection } from './HowItWorksSection'
export { default as PricingSection } from './PricingSection'
